# configuration for "master" branch
# build in Release mode
-
  environment:
    packageVersion: 0.3.0

  version: '{branch}-v0.3.0-{build}'
  image: Visual Studio 2017

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: true

  skip_branch_with_pr: true

  before_build:
    - cmd: nuget restore

  after_test:
    - cmd: nuget pack Source\Lib\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.nuspec -OutputDirectory Build\Lib\RangeIt\%CONFIGURATION% -BasePath Source\Lib\%APPVEYOR_PROJECT_NAME% -Properties buildConfig=Release
    - ps: Get-ChildItem .\Build\Lib\RangeIt\Release\RangeIt*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  build:
    verbosity: minimal

  branches:
    only:
      - master

  test:
    assemblies:
      - Build\Tests\RangeIt.Tests\Release\RangeIt.Tests.dll

  configuration: Release

  artifacts:
    - path: Build\Lib\RangeIt\Release\RangeIt.dll
      name: Assembly
    - path: Build\Lib\RangeIt\Release\RangeIt.pdb
      name: AssemblyPDB
    - path: Build\Lib\RangeIt\Release\RangeIt.xml
      name: DocumentationXML

  deploy:
    - provider: NuGet
      api_key:
        secure: sjU4hS/2R00uglMrDRFL2J4F5HccKXtd+AOfK5XStBv/p4+ZoHjA3L7LNLklrkBr
      skip_symbols: true
      symbol_server:
      artifact: RangeIt.$(packageVersion).nupkg
      on:
        appveyor_repo_tag: true

# configuration for all branches starting from "dev-"
# build in Debug mode
-
  version: '{branch}-{build}'
  image: Visual Studio 2017

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: true

  skip_branch_with_pr: true

  before_build:
    - cmd: nuget restore

  after_test:
    - cmd: nuget pack Source\Lib\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.nuspec -OutputDirectory Build\Lib\RangeIt\%CONFIGURATION% -BasePath Source\Lib\%APPVEYOR_PROJECT_NAME% -Properties buildConfig=Debug
    - ps: Get-ChildItem .\Build\Lib\RangeIt\Debug\RangeIt*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  build:
    verbosity: minimal

  branches:
    only:
      - dev
      - /dev-.*/

  test:
    assemblies:
      - Build\Tests\RangeIt.Tests\Debug\RangeIt.Tests.dll

  configuration: Debug

  artifacts:
    - path: Build\Lib\RangeIt\Debug\RangeIt.dll
      name: DebugAssembly
    - path: Build\Lib\RangeIt\Debug\RangeIt.pdb
      name: DebugAssemblyPDB
    - path: Build\Lib\RangeIt\Debug\RangeIt.xml
      name: DocumentationXML

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  version: '{branch}-{build}'
  image: Visual Studio 2017

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: true

  skip_branch_with_pr: true

  before_build:
    - cmd: nuget restore

  build:
    verbosity: minimal

  test:
    assemblies:
      - Build\Tests\RangeIt.Tests\Debug\RangeIt.Tests.dll

  configuration: Debug

  artifacts:
    - path: Build\Lib\RangeIt\Debug\RangeIt.dll
      name: DebugAssembly
    - path: Build\Lib\RangeIt\Debug\RangeIt.pdb
      name: DebugAssemblyPDB
    - path: Build\Lib\RangeIt\Debug\RangeIt.xml
      name: DocumentationXML
